# # docker-compose.yml
version: '3.9'
services:
  postgres:
    container_name: "motive-postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - motive-db:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  motive:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: host.docker.internal
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:3000'
    networks:
      - backend
volumes:
  motive-db:

networks:
  backend:


# version: "3.9"
# services:
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports: 
#       - '5432:5432'
#     volumes:
#       - motive-db:/var/lib/postgresql/data

#   motive:
#     build:
#       context: .
#     environment:
#       DB_SCHEMA: postgres
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       DB_HOST: postgres
#     depends_on:
#       - postgres
#     ports:
#       - '3000:3000'
        
# volumes:
#   motive-db:
  