name: Deploy on main push
run-name: ${{ github.actor }} is deploying to EC2 via Github Actions
on:   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start docker
      run: sudo sh src/restart.sh
